### ISSUE TITLE
Feature request: Ability to capture screenshots of the list of filtered components.

### ISSUE THREAD

**Issue by davidmoshal** [asvae/vue-book#24]
Feature request: ability to automatically capture a snapshot of the components as either an html site or a pdf.

Usage: 
- filter the component tree
- click 'snapshot as html site' or 'snapshot as pdf'
- snapshot is created of all of the filtered components

**Comment by davidmoshal** [comment]
Sure, I'm in the process of rewriting an app to use a different ui framework, Vue-Design-Ant.  

It would be nice to have pictures of all the 150 old components to look at as the old app has broken tool dependencies.

Additionally having a portfolio of all the components would be great to share with customers.

Furthermore, because Vue is data driven, you could load a vuex instance and then generate the portfolio. This could be an easy way to have a portfolio with different component states or themes.

Lastly, if possible (I realize this wouldn't work in all browsers) you could run the portfolio with different browsers.

So usages would be to capture static view of a portfolio:

A) for a components that are not under active development and which may not run with future tool dependencies.

B) for easy communication with team and customers.

C) to easily see the effect of different themes or states.

D) for visual testing with different browsers (if possible).

**Comment by asvae** [comment]
It seems to me that what you've spoken about is easily achievable with current set of features.

1) If you want separate site with components - we have a couple of technical solutions:
* separate build
* .env + webpack definePlugin.
Again here I don't exactly understand how static site or pdf is better than regular spa.

For projects I participated in we have built demos with staging build and disabled them on production. Which covers communication aspect, I suppose.

2) Regarding themes, you can do a wrapper component of some sorts in router. `vue-book` is not required to take route position. In wrapper component you can do small overlay on the side with theme switch and other global configs so that other devs or customers can play around.

---------------

Or did you mean something like this? https://foundation.zurb.com/sites/docs/kitchen-sink.html
Essentially a lot of components on the same page?

**Comment by asvae** [comment]
That's quite exotic :D.

So one of your project has dead dependency chain and you would like a "screenshot backup" to keep for similar future projects in case dependencies go broken? You do not intend to resurrect your current project?

Have you used `package.lock` or `yarn.lock`?

Overall, I think it's much better for devs to work on actual working components (which you can easily achieve with staging site) rather than pdfs or images.

**Comment by davidmoshal** [comment]
> That's quite exotic :D.

I like exotic!

> So one of your project has dead dependency chain and you would like a "screenshot backup" to keep for similar future projects in case dependencies go broken? You do not intend to resurrect your current project?

correct!

> Have you used package.lock or yarn.lock?

Yes, but it's not working, there are a couple of issues:
a) one of the deps have a vulnerability and has been removed, i can't even go back to the package.lock version!
b) the entire toolchain has moved on (npm, tsc, etc) and all of that has to be rolled back too.

> Overall, I think it's much better for devs to work on actual working components (which you can easily achieve with staging site) rather than pdfs or images.

I agree, but this is just a backup, and also, useful to generate an entire portfolio with different theme settings.


Here is my eval of potential candidate libraries:


All browsers, 14,000 stars:
https://github.com/niklasvh/html2canvas

Different resolutions, 8,000 stars:
https://github.com/sindresorhus/pageres

The StoryBook version:
https://github.com/tsuyoshiwada/storybook-chrome-screenshot

This one will work with chrome and firefox, 400 stars:
https://github.com/juliangruber/capture-screenshot  

PhantomJS webkit 2000 stars:
https://github.com/brenden/node-webshot

A simple library using puppeteer (headless Chrome):
https://github.com/bouzuya/screenshot-testing-js
also:
https://github.com/dferber90/jsdom-screenshot

Another all-browser library:
https://github.com/Moventes/html2canvas

A pdf generator (also puppeteer):
https://github.com/SynergiTech/chrome-pdf

Others: 
https://github.com/gemini-testing/gemini

NOTE: apart from capturing the filtered list of urls, and a couple of buttons, there isn't much that Vuebook needs to do, this can either run server side (limited to chrome and firefox headless versions), or run in the actual browser.

I'll look into this further and report back findings.

**Comment by asvae** [comment]
Yep. This will create a set of snapshots for comparison that will be kept with project.

I got several more specific ideas, which I surmised to [this issue](https://github.com/asvae/vue-book/issues/25).

**Comment by asvae** [comment]
Moved to #25
